commerce_rma.rma_reason.*:
  type: config_entity
  label: 'RMAReason config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
